CREATE TABLE licao (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    projeto VARCHAR(50) NOT NULL,
    texto VARCHAR(500) NOT NULL,
    tipo VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

